- name: Redeploy vizix_statemachine
  hosts: all
  become: yes
  tasks:
    - name: "Check if vizix_statemachine is up"
      shell: docker service ps {{item}}
      with_items:
        - vizix_statemachine-api-dashboard-configuration

    - name: Stop vizix_statemachine
      shell: docker service rm vizix_statemachine-api-dashboard-configuration
      args:
        chdir: /opt/vizix/shopcx

    - name: Start vizix_statemachine
      shell: docker stack deploy vizix --with-registry-auth -c statemachine-api-dashboard-configuration.yaml
      args:
        chdir: /opt/vizix/shopcx

    - name: Wait until vizix_statemachine is up
      shell: docker service ls | grep vizix_statemachine
      register: tools_status
      until: tools_status.stdout.find('1/1') != -1
      delay: 30
      retries: 20
